# Site settings
title: Embedded.Systems | A blog about everything embedded and more
description: "A blog about embedded systems and more."
url: "https://www.embedded.systems"
github_username: sijinwoo


# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins: 
  - jekyll-paginate

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem


# Custom variables
version: "1.2.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
