# Site settings
title: Embedded.Systems | A blog about everything embedded and more
description: "A blog about embedded systems and more."
#url: "http://www.sikenderaliashraf.com/kendiser5000-blog/
#build_url:"
github_username: kendiser5000
author:
  name: "Embedded.Systems"
  email: "hello@jacoporabolini.com"
  url: "http://www.google.com"

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

baseurl: "Embedded.Systems"
# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins: 
  - jekyll-paginate

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem


# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
